language: node_js
node_js:
- '12'
sudo: false
install:
- npm install --silent
script:
- npm run package
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: BN5cxBoftyqpOns04Vsh7expIUmQEbZtLsujrUBeB0mcID7bO4m5CjB+CC9dv++K00pIo5qpqKjQmGzo8Yeo7jI1+hhywcC8XVSwWSQklDNVeE1XdC2MHIKRQ3xZDPcVHK2AViv3NBMBPc9t8vP9xPKolJ+47FWVL2DxGp2zxGVhi1N3PqW9hkXnAVXgF4UsYJXHzWQWyjd7gSjIcPHvMU/1p9ZEpHF86XOyMgdPV6fUDnCvASElo5H638o9DfhecGm/pLEI+/7/qhvqgysDZILNEkEU9/wOQ0sacSJOrejvS/1yo8tyR1xKkQGoGgeDi9pF0TlPid3jWxmdlaA9FmwDFpp/oinV5CaelMFADDYFHYXCSXg0L1HfJuEdJ2vib8TtjyaMMfDAR0ZW9RSTPIdRg6ERVuQyS+cR8dfEi3wUbz/fXMLX5e0m55c9KbMmrzieKXOtmhCh52dU8aeb0wq3PfBl8AI65KlhZqEoJeNLxFqTEE9pJR5WgWFKZIuv1YQvoOC6zgP4ltkJm3Y9tNQhsP6JaETukQ2Nuhin3PJnvKBoKk4YhKKh5lZZBFl3mFfSGfLVQ5834ss6d6tprUTzy23LuN7JHGh1+q/TZKmNu3F5rOCcwcTSfcbjilYT18WXhR69frYzcVkGVgi91QSZf18q3diIcPpN9pOF80w=
  file_glob: true
  file: dist/dat-fox-helper-*
  on:
    repo: sammacbeth/dat-fox-helper
    tags: true
